### ISSUE TITLE
Improve snippet storage

### ISSUE THREAD

**Issue by aaronjanse** [aaronduino/snippet-manager#4]
At the moment, snippets are stored in a json file.
This should be probably be changed to a series of text files in a flat directory.

**Comment by WebMatrixware** [comment]
Any chance of moving this to something like SQLite to help it scale better and stay fast as your catalog grows?

**Comment by aaronjanse** [comment]
Sounds like a great idea!

If you are willing to contribute a pull request, I'd love it.

If not, I'll try to find time in the next few weeks to work on it, but it might take a while.

-------- Original Message --------
